language: node_js
node_js:
 - "10"
 - "12"
 - "14"
 - "node"

script:
 - npm run lint
 - npm run validate
 - npm run test:integration
 - npm run test:unit
 - npm run test:system
 - npm run test:deploy

after_success:
 - npm run coveralls
